[package]
name = "eventos"
version = "0.1.0"
authors = ["DiogoSemedo <diogo.semedo.uc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.19.1"